In [77]:
import numpy as np

************************
**Basic Array Creation**
************************

In [78]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [79]:
a = [1,2,3,4, "hello"]
a

[1, 2, 3, 4, 'hello']

In [80]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [81]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [82]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

******************************
**Array Generation Functions**
******************************

In [83]:
rng = np.arange(1,16,2)
rng

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [84]:
arr = np.zeros((4, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
arr = np.ones((2,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [86]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

*******************************
**Random Generation Functions**
*******************************

In [87]:
arr = np.random.rand(10)    # Normalization
arr

array([0.35676433, 0.50205541, 0.85788748, 0.84062948, 0.08475491,
       0.85481887, 0.89645652, 0.22529015, 0.53286211, 0.95605985])

In [88]:
arr = np.random.randn(10)   # Standardization
arr

array([ 0.4790683 ,  3.2054381 ,  0.45546395, -0.09403337, -0.84416253,
        0.10555348, -2.12182113, -2.95714429, -0.72666121,  0.45495388])

In [89]:
arr = np.random.randint(10,20,10)
arr

array([10, 10, 13, 19, 18, 15, 15, 12, 15, 11], dtype=int32)

********************
**Array Attributes**
********************

In [90]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
arr.shape

(3, 3)

In [92]:
arr.size

9

In [93]:
arr.dtype

dtype('int64')

*****************
**Array Methods**
*****************

In [94]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
arr.min()

np.int64(1)

In [96]:
arr.max()

np.int64(9)

In [97]:
arr.sum()

np.int64(45)

In [98]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [99]:
arr.mean()

np.float64(5.0)

In [100]:
arr.std()

np.float64(2.581988897471611)

In [101]:
arr.argmax()

np.int64(8)

**************************
**Reshaping and Resizing**
**************************

In [102]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [103]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [116]:
arr = np.arange(1,31)
arr.resize(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])