In [1]:
import numpy as np

*****************************************
**NUMPY INDEXING AND SLICING OF VECTORS**
*****************************************

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr2 = arr[1:5:]
arr2

array([12, 13, 14, 15])

In [8]:
arr[5]

np.int64(16)

*****************************************
**NUMPY INDEXING AND SLICING OF MATRIX**
*****************************************

In [20]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [21]:
arr[0]

array([1, 2, 3, 4, 5])

In [22]:
arr[:, 0]

array([ 1,  6, 11, 16, 21, 26])

In [26]:
slice = arr[3:, 3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

*****************************************
**BOOLEAN INDEXING**
*****************************************

In [27]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [29]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])