In [15]:
import numpy as np

*****************************************
**VALID SUDOKU**
*****************************************

In [16]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [17]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [18]:
np.sum(s, axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [87]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


*****************************************
**GENERAL QUESTIONS**
*****************************************

In [174]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [175]:
#Get the shape of the matrix
print(data.shape)

(5, 3)


In [176]:
#Find the average age of students.
print(data[:,0:1].mean())

18.4


In [177]:
#Extract Math marks of all students.
print(data[:,1])

[85 92 76 65 90]


In [178]:
#Find the highest Science mark.
print(data[:, 2:].max())

95


In [179]:
#Get details of the student who scored more than 90 in Math.
print(data[data[:,1] > 90])

[[19 92 88]]


In [180]:
#Increase Math marks of all students by 5.
print(data[:,1] + 5)

[90 97 81 70 95]


In [181]:
#Find how many students are younger than 19.
print(len(data[data[:,0] < 19]))

3


In [182]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [183]:
#Get data of students who scored at least 80 in both subjects.
print(data[(data[:,1] >= 80) & (data[:,2] >= 80)])

[[19 92 88]
 [20 90 85]]


In [187]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75, 2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])