In [1]:
import numpy as np

*****************************************
**ARRAY OPERATION**
*****************************************

*Arithmetic Operations*

In [4]:
# Size of arrays must be same 
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a2 / a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [7]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

*Array Broacasting*

In [8]:
l = [10,20,30,40]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50])

In [9]:
arr2 = np.arange(1,26).reshape(5,5)
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

*Deep & Shallow Copy*

In [18]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [20]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
b = a        # Use .copy() for deep copy 
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
a            # A shallow copy

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

*Matrix Operations*

In [24]:
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])

In [25]:
mat1

array([[1, 2],
       [3, 4]])

In [26]:
mat2

array([[5, 6],
       [7, 8]])

In [28]:
np.dot(mat1, mat2)

array([[19, 22],
       [43, 50]])

In [29]:
mat1.T

array([[1, 3],
       [2, 4]])

*****************************************
**ADVANCE ARRAY MANIPULATION**
*****************************************

*Stacking Array*

In [31]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [32]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

*Splitting Array*

In [44]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [49]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]